name: fireman
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy
  - pandas
  - pyreadr
  - notebook
  - scikit-learn
  - matplotlib
  - pip
  - pip:
      # works for regular pip packages
      - arff