name: fireman
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy
  - pandas
  - pyreadr
  - jupyterlab
  - scikit-learn
  - matplotlib
  - pip:
      # works for regular pip packages
      - arff